export const aboutUS = [
  {
    id: 1,
    cover: "/assets/image1.jpg",
    title: "Speedy Delivery",
    text: "We have a fast and effiecient delivery system with 24/7 support.",
  },
  {
    id: 2,
    cover: "/assets/image2.jpg",
    title: "Exciting Taste",
    text: "We derive our great taste from our careful seleted ingredent gotton from the best sources.",
  },
  {
    id: 3,
    cover: "/assets/imge3.jpg",
    title: "Best Offer",
    text: "We have on our menu the offer you can get anywhere.",
  },
];
export const foodItems = [
  {
    id: 1,
    cover: "/assets/foodimage.jpg",
    foodName: "Soft Drink",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 2,
    cover: "/assets/foodimage2.avif",
    foodName: "Salad",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(34 views)",
    foodPrice: "$2.90",
  },
  {
    id: 3,
    cover: "/assets/foodimage3.avif",
    foodName: "Cake",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(60 views)",
    foodPrice: "$12.1",
  },
  {
    id: 4,
    cover: "/assets/foodimage3.avif",
    foodName: "Cake ",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 5,
    cover: "/assets/foodimage4.avif",
    foodName: "Rice",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$29.9",
  },
  {
    id: 6,
    cover: "/assets/foodimage5.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 7,
    cover: "/assets/foodimage6.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 8,
    cover: "/assets/foodimage7.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
];
export const BreakFast = [
  {
    id: 1,
    cover: "/assets/foodimage9.avif",
    foodName: "Soft Drink",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 2,
    cover: "/assets/foodimage10.avif",
    foodName: "Salad",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(34 views)",
    foodPrice: "$2.90",
  },
  {
    id: 3,
    cover: "/assets/foodimage11.jpg",
    foodName: "Cake",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(60 views)",
    foodPrice: "$12.1",
  },
  {
    id: 4,
    cover: "/assets/foodimage12.avif",
    foodName: "Cake ",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 5,
    cover: "/assets/foodimage4.avif",
    foodName: "Rice",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$29.9",
  },
  {
    id: 6,
    cover: "/assets/foodimage5.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 7,
    cover: "/assets/foodimage6.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 8,
    cover: "/assets/foodimage7.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
];
export const dinnerItems = [
  {
    id: 1,
    cover: "/assets/foodimage.jpg",
    foodName: "Soft Drink",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 2,
    cover: "/assets/foodimage2.avif",
    foodName: "Salad",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(34 views)",
    foodPrice: "$2.90",
  },
  {
    id: 3,
    cover: "/assets/foodimage3.avif",
    foodName: "Cake",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(60 views)",
    foodPrice: "$12.1",
  },
  {
    id: 4,
    cover: "/assets/foodimage3.avif",
    foodName: "Cake ",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 5,
    cover: "/assets/foodimage4.avif",
    foodName: "Rice",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$29.9",
  },
  {
    id: 6,
    cover: "/assets/foodimage5.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 7,
    cover: "/assets/foodimage6.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
  {
    id: 8,
    cover: "/assets/foodimage7.avif",
    foodName: "Pop Corn",
    foodDescription: "Lorem ipsum dolor sit.",
    foodnView: "(89 views)",
    foodPrice: "$27.9",
  },
];

export const teamMember = [
  {
    id: 1,
    cover: "/assets/chefImage1.avif",
    chefName: "Oliver Aguilerra",
  },
  {
    id: 2,
    cover: "/assets/chefImage2.avif",
    chefName: "Alice Melbourne",
  },
  {
    id: 3,
    cover: "/assets/chefImage3.avif",
    chefName: "John Doe",
  },
  {
    id: 4,
    cover: "/assets/chefImage4.avif",
    chefName: "Oliver Aguilerra",
  },
];

export const blog = [
  {
    id: 1,
    cover: "/assets/blogImage1.avif",
    posterName: "Ayantade Olamide",
    postDate: "JAN, 19, 2023",
    blogTitle: "What Do You Think AboutCheese Pizza Recipes?",
    blogText:
      "Financial experts support or help you to to find out which way you can raise your funds more...",
    blogLink: "34",
    blogComment: "12",
  },
  {
    id: 2,
    cover: "/assets/blogImage2.avif",
    posterName: "Chef Adedigba",
    postDate: "JAN, 22, 2023",
    blogTitle: "What Do You Think AboutCheese Pizza Recipes?",
    blogText:
      "Financial experts support or help you to to find out which way you can raise your funds more...",
    blogLink: "49",
    blogComment: "10",
  },
  {
    id: 1,
    cover: "/assets/blogImage3.jpg",
    posterName: "Ayantade Olamide",
    postDate: "FEB, 28, 2023",
    blogTitle: "What Do You Think AboutCheese Pizza Recipes?",
    blogText:
      "Financial experts support or help you to to find out which way you can raise your funds more...",
    blogLink: "12",
    blogComment: "6",
  },
];
